name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_BEFORE_ALL_LINUX: "bash {package}/scripts/setup-centos8.sh"
          CIBW_BEFORE_ALL_MACOS: "bash {package}/scripts/setup-macos.sh"
          # CIBW_SOME_OPTION: value
        #    ...
        with:
          # package-dir: pyvelox
          output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl