name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11]
    steps:
      - uses: actions/checkout@v3
      - if: matrix.os == 'macos-11'
        run: echo "/usr/local/opt/openssl@1.1/bin" >> $GITHUB_PATH
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_BEFORE_ALL_LINUX: "ls -R {package}/third_party && bash {package}/scripts/setup-velox-torcharrow.sh false"
          CIBW_BEFORE_ALL_MACOS: "bash {package}/scripts/setup-macos.sh"
          # CIBW_SOME_OPTION: value
        #    ...
        with:
          # package-dir: pyvelox
          output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl