name: Build

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-11]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - if: matrix.os == 'macos-11'
        run: |
          echo "OPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/" >> $GITHUB_ENV
        
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          # required for predv/pwritev
          MACOSX_DEPLOYMENT_TARGET: "11.0"
          CIBW_ARCHS: "x86_64"
          CIBW_BUILD: "cp39-* cp310-* cp311-*"
          CIBW_SKIP: "*musllinux*"
          CIBW_BEFORE_ALL_LINUX: "bash {package}/scripts/setup-velox-torcharrow.sh false"
          CIBW_BEFORE_ALL_MACOS: "bash {package}/scripts/setup-macos.sh"
        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl