# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Build & Push Docker Images

on:
  pull_request:
    paths:
      - scripts/docker/*.dockerfile
      - scripts/setup-*.sh
      - .github/workflows/docker.yml
      - docker-compose.yml
  push:
    branches: [main, docker-refactor]
    paths:
      - scripts/docker/*.dockerfile
      - scripts/setup-*.sh
      - .github/workflows/docker.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  BASE_NAME: ghcr.io/assignuser
jobs:
  multi-arch-base:
    name: Build ${{ matrix.target }} Image on ${{ matrix.os.platform }}
    runs-on: ${{ matrix.os.runner }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - {runner: ubuntu-24.04-arm, platform: arm64}
          - {runner: ubuntu-24.04, platform: amd64}
        target: [ci, pyvelox]

    steps:
      - name: Free Disk Space
        run: |
          # 15G
          sudo rm -rf /usr/local/lib/android || :
          # 5.3GB
          sudo rm -rf /opt/hostedtoolcache/CodeQL || :

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: apache/infrastructure-actions/stash/restore@3354c1565d4b0e335b78a76aedd82153a9e144d4
        with:
          path: /tmp/docker_cache
          key: docker-cache-${{ matrix.target }}-${{ matrix.os.platform }}

      - name: Bake Images
        id: bake
        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        with:
          targets: ${{ matrix.target }}
          set: |
            *.tags=
            *.output=type=image,push-by-digest=true,name=${{ env.BASE_NAME }}/velox-dev,name-canonical=true,push=${{ github.event_name != 'pull_request' }}
            *.cache-to=type=local,dest=/tmp/docker_cache_new,compression=zstd,mode=max
            *.cache-from=type=local,src=/tmp/docker_cache
            *.cache-from=type=registry,ref=ghcr.io/facebookincubator/velox-dev

      - uses: apache/infrastructure-actions/stash/save@3354c1565d4b0e335b78a76aedd82153a9e144d4
        if: ${{ ! cancelled() }}
        with:
          # We cache to a new directory to keep the cache small
          path: /tmp/docker_cache_new
          key: docker-cache-${{ matrix.target }}-${{ matrix.os.platform }}

      - name: Export digests
        env:
          METADATA: ${{ steps.bake.outputs.metadata }}
          DIGEST_DIR: ${{ runner.temp }}/digests
        run: |
          mkdir -p "$DIGEST_DIR"
          cd "$DIGEST_DIR" || exit 1
          echo "$METADATA" | jq -r 'to_entries[] | ( .value["image.name"] | split("/")[-1] ) +
            " " + ( .value["containerimage.digest"] | split(":")[-1] )' | \
            while read -r image_name digest; do
              image_name=$( echo "$image_name" | tr ':' '_' )
              mkdir -p "$image_name"
              touch "$image_name/$digest"
            done
          ls -laR

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.target }}-${{ matrix.os.platform }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    if: ${{ github.event_name != 'pull_request' }}
    needs: multi-arch-base
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          for dir in */; do
            dir=${dir%/}  # Remove trailing slash

            # Get the base image name (e.g., velox-dev:adapters)
            name_with_tag=$(echo "$dir" | tr '_' ':')

            image_name="$BASE_NAME/$name_with_tag"
            args=("-t $image_name")

            pushd "$dir" || exit 1
            # Add each digest to the command
            for digest_file in *; do
              args+=("$BASE_NAME/velox-dev@sha256:$digest_file")
            done
            popd || exit 1

            echo docker buildx imagetools create "${args[@]}"
            docker buildx imagetools create "${args[@]}"
          done

  linux:
    if: false
    name: Build and Push ${{ matrix.name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Centos 9
            file: scripts/docker/centos.dockerfile
            tags: ghcr.io/facebookincubator/velox-dev:centos9
          - name: Pyvelox
            file: scripts/docker/pyvelox.dockerfile
            tags: ghcr.io/facebookincubator/velox-dev:pyvelox
          - name: Dev
            file: scripts/docker/ubuntu-22.04-cpp.dockerfile
            args: ''
            tags: ghcr.io/facebookincubator/velox-dev:ubuntu-22.04

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build and Push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: ${{ matrix.file }}
          build-args: ${{ matrix.args }}
          push: ${{ github.repository == 'facebookincubator/velox' && github.event_name != 'pull_request'}}
          tags: ${{ matrix.tags }}

  linux-needs:
    name: Build and Push ${{ matrix.name }}
    needs: linux
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Adapters
            file: scripts/docker/adapters.dockerfile
            tags: ghcr.io/facebookincubator/velox-dev:adapters
          - name: Presto Java
            file: scripts/docker/prestojava-container.dockerfile
            args: PRESTO_VERSION=0.290
            tags: ghcr.io/facebookincubator/velox-dev:presto-java
          - name: Spark server
            file: scripts/docker/spark-container.dockerfile
            args: SPARK_VERSION=3.5.1
            tags: ghcr.io/facebookincubator/velox-dev:spark-server

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build and Push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: ${{ matrix.file }}
          build-args: ${{ matrix.args }}
          push: ${{ github.repository == 'facebookincubator/velox' && github.event_name != 'pull_request'}}
          tags: ${{ matrix.tags }}
