name: Build & Push Docker Images

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - scripts/*.dockfile
      - scripts/*.dockerfile
      - .github/workflows/docker.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - uses: actions/checkout@v3
      
      - name: Build and Push circle-ci
        uses: docker/build-push-action@v3
        with:
          context: scripts
          file: scripts/circleci-container.dockfile
          build-args: cpu_target=avx
          push: true # ${{ github.repository == 'facebookincubator/velox' && github.event != 'pull_request'}}
          tags: ghcr.io/assignuser/velox-dev:circleci-avx

      - name: Build and Push Check
        uses: docker/build-push-action@v3
        with:
          context: scripts
          file: scripts/check-container.dockfile
          build-args: cpu_target=avx
          push: true # ${{ github.repository == 'facebookincubator/velox' && github.event != 'pull_request'}}
          tags: ghcr.io/assignuser/velox-dev:check-avx

      - name: Build and Push velox-torcharrow
        uses: docker/build-push-action@v3
        with:
          context: scripts
          file: scripts/velox-torcharrow-container.dockfile
          build-args: cpu_target=avx
          push: true # ${{ github.repository == 'facebookincubator/velox' && github.event != 'pull_request'}}
          tags: ghcr.io/assignuser/velox-dev:torcharrow-avx

      - name: Build and Push Dev-Image 
        uses: docker/build-push-action@v3
        with:
          file: scripts/ubuntu-22.04-cpp.dockerfile
          push: true #${{ github.repository == 'facebookincubator/velox' && github.event != 'pull_request'}}
          tags: ghcr.io/assignuser/velox-dev:amd64-ubuntu-22.04-avx

