name: Trigger Zizmor and yamllint lints

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    if: false
    runs-on: "ubuntu-latest"
    steps:
      - run: ${{ github.event.pull_request.title }}
